somke test

diff --git a/.github/workflows/smoke_test.yml b/.github/workflows/smoke_test.yml
--- a/.github/workflows/smoke_test.yml
+++ b/.github/workflows/smoke_test.yml
@@ -1,12 +1,66 @@
-name : smoke Testing for Infra and Networking
+name: Smoke Testing for Infra and Networking
 
 on:
-  workflow_call
+  workflow_call:
 
 jobs:
-  working-job:
+  smoke:
     runs-on: ubuntu-latest
 
     steps:
-      - name : Echo Message
-        run : echo "Smoke Test is working successfully ✅"
+      - uses: actions/checkout@v4
+
+      - uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::865147227423:role/github-action
+          aws-region: us-east-1
+      - name: Upload smoke_test.py on AWS
+        run: |
+            aws s3 mb s3://865147227423-devops-scripts --region us-east-1
+            aws s3 cp ./smoke_test.py \
+            s3://865147227423-devops-scripts/smoke_test.py \
+            --region us-east-1
+
+      - name: Run smoke test on Fleet
+        id: smoke
+        run: |
+          CMD_ID=$(aws ssm send-command \
+            --targets "Key=tag:App,Values=flask" \
+            --document-name "AWS-RunShellScript" \
+            --parameters '{
+              "commands":[
+                "aws s3 cp s3://865147227423-devops-scripts/smoke_test.py /tmp/smoke_test.py",
+                "python3 /tmp/smoke_test.py",
+                "rm -f /tmp/smoke_test.py"
+              ]
+            }' \
+            --query 'Command.CommandId' \
+            --output text \
+            --region us-east-1)
+
+          echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
+
+      - name: Show Results
+        run: |
+          sleep 30
+
+          aws ssm list-command-invocations \
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --output text
+
+          FAILED=$(aws ssm list-command-invocations \
+            --command-id "${{ steps.smoke.outputs.cmd_id }}" \
+            --query "length(CommandInvocations[?Status=='Failed'])" \
+            --output text \
+            --region us-east-1)
+
+          echo "FAILED=$FAILED"
+
+          if [ "${FAILED:-0}" -gt 0 ]; then
+            echo "::error::Smoke test failed on Fleet"
+            exit 1
+          fi
+
+          echo "✅ Smoke test passed."
