pipeline

diff --git a/.github/workflows/test_fleet_health.yml b/.github/workflows/test_fleet_health.yml
--- a/.github/workflows/test_fleet_health.yml
+++ b/.github/workflows/test_fleet_health.yml
@@ -1,8 +1,7 @@
-name: Test Fleet health and Env Variables
+name: Test fleet Health & Env Variables
 
 on:
   workflow_call:
-
 
 permissions:
   id-token: write
@@ -11,10 +10,11 @@ permissions:
 jobs:
   test:
     runs-on: ubuntu-latest
+
     steps:
       - uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::720800607391:role/github-action-deploy-role
+          role-to-assume: arn:aws:iam::865147227423:role/github-actions
           aws-region: us-east-1
 
       - name: Fleet Health Checks
@@ -23,36 +23,42 @@ jobs:
           CMD_ID=$(aws ssm send-command \
             --targets "Key=tag:App,Values=flask" \
             --document-name "AWS-RunShellScript" \
-            --parameters '{"commands":[
-              "hostname -I",
-              "docker --version 2>/dev/null  echo DOCKER NOT INSTALLED",
-              "aws --version 2>/dev/null  echo AWS CLI NOT INSTALLED",
-              "mysql --version 2>/dev/null || echo DOCKER NOT INSTALLED",
-              "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1"
-              ]}' \
-            --query 'Command.CommandId' --output text \
+            --parameters '{
+              "commands": [
+                "hostname -I",
+                "docker --version 2>/dev/null || echo DOCKER NOT INSTALLED",
+                "aws --version 2>/dev/null || echo AWS CLI NOT INSTALLED",
+                "mysql --version 2>/dev/null || echo MYSQL NOT INSTALLED",
+                "aws ssm get-parameters-by-path --path /application/banking --with-decryption --region us-east-1"
+              ]
+            }' \
+            --query "Command.CommandId" \
+            --output text \
             --region us-east-1)
-          echo "cmd_id"=$"CMD_ID" >> $GITHUB_OUTPUT
-      
-      
+
+          echo "cmd_id=$CMD_ID" >> "$GITHUB_OUTPUT"
+
       - name: Show Results
-        run: | 
+        run: |
           sleep 20
+
           aws ssm list-command-invocations \
-            --command-id "${{steps.health.outputs.cmd_id}}" --details \
-            --region us-east-1
-            --query "CommandInvocations[*].{Instance:InstanceId,Status,IP:CommandPlugins[0].Output}" \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --details \
+            --region us-east-1 \
+            --query "CommandInvocations[*].{Instance:InstanceId,Status:Status,IP:CommandPlugins[0].Output}" \
             --output text
-          
+
           FAILED=$(aws ssm list-command-invocations \
-            --command-id "${{steps.health.outputs.cmd_id}}" --details \
+            --command-id "${{ steps.health.outputs.cmd_id }}" \
+            --details \
             --query "length(CommandInvocations[?Status=='Failed'])" \
             --output text \
-            --region us-east-1
-            )
+            --region us-east-1)
 
-          [ "$FAILED" -gt 0 ] && \
-          echo "::error::Health Check Failed on $FAILED instances" && \
-          exit 1
+          if [ "$FAILED" -gt 0 ]; then
+            echo "::error::Health Check Failed on $FAILED instances"
+            exit 1
+          fi
 
           echo "ALL Instances Healthy ✅"
